name: BUILD
on:
   # События, которые запускают jobs
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

# jobs запускаются параллельно, если не указана последовательность
jobs:
    # Название job вы можете назвать как угодно
    my_build_job:
      # Операционная система в виртуальной машине, в которой запускаются процессы
      runs-on: ubuntu-latest
        # Шаги
      steps:
        # Actions от github: проверяет репозиторий, гит и т.д.
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Run a one-line script
          run: |
            echo Build identidock!
            pip install -r requirements.txt
            python tests.py
            python identidock.py

